package pt.daniel.odbc

import com.sun.jna.Pointer
import com.sun.jna.ptr.IntByReference
import pt.daniel.odbc.interop.OdbcApi
import pt.daniel.odbc.interop.OdbcDiagnostics
import java.sql.*
import java.util.Properties
import java.util.concurrent.Executor

/**
 * Implementação de [Connection] que representa uma sessão ativa com uma fonte de dados ODBC.
 *
 * Suporta:
 * - Criação de Statement e PreparedStatement
 * - Transações manuais (commit/rollback via SQLEndTran)
 * - AutoCommit configurável
 * - DatabaseMetaData via SQLGetInfo + SQLTables/SQLColumns
 *
 * @param api              API nativa ODBC injetada (permite mocking em testes).
 * @param envHandle        Handle do ambiente ODBC (SQL_HANDLE_ENV).
 * @param connectionHandle Handle da conexão ODBC (SQL_HANDLE_DBC).
 */
class OdbcConnection(
    internal val api: OdbcApi,
    private val envHandle: Pointer?,
    internal val connectionHandle: Pointer?,
    internal val charset: java.nio.charset.Charset
) : Connection {

    private var closed = false
    private var autoCommit = true

    /** Indica que a conexão nativa está morta (erro de comunicação detetado). */
    @Volatile
    private var connectionDead = false

    // --- Métodos com lógica ODBC real ---

    override fun createStatement(): Statement {
        checkNotClosed()
        return OdbcStatement(this, api, allocateStatementHandle(), charset)
    }

    override fun prepareStatement(sql: String?): PreparedStatement {
        checkNotClosed()
        requireNotNull(sql) { "O SQL não pode ser nulo" }
        return OdbcPreparedStatement(this, api, allocateStatementHandle(), sql, charset)
    }

    override fun close() {
        if (!closed) {
            try {
                api.SQLDisconnect(connectionHandle)
                api.SQLFreeHandle(OdbcApi.SQL_HANDLE_DBC.toShort(), connectionHandle)
                api.SQLFreeHandle(OdbcApi.SQL_HANDLE_ENV.toShort(), envHandle)
            } finally {
                closed = true
            }
        }
    }

    override fun isClosed(): Boolean = closed

    // --- Transações ---

    override fun setAutoCommit(autoCommit: Boolean) {
        checkNotClosed()
        val value = if (autoCommit) OdbcApi.SQL_AUTOCOMMIT_ON else OdbcApi.SQL_AUTOCOMMIT_OFF
        val result = api.SQLSetConnectAttr(
            connectionHandle,
            OdbcApi.SQL_ATTR_AUTOCOMMIT,
            Pointer(value.toLong()),
            0
        )
        if (!OdbcApi.isSuccess(result)) {
            val diag = OdbcDiagnostics.getDiagMessage(api, OdbcApi.SQL_HANDLE_DBC.toShort(), connectionHandle)
            throw SQLException("Não foi possível alterar autoCommit: $diag")
        }
        this.autoCommit = autoCommit
    }

    override fun getAutoCommit(): Boolean = autoCommit

    override fun commit() {
        checkNotClosed()
        if (autoCommit) throw SQLException("Não é possível fazer commit em modo autoCommit")
        val result = api.SQLEndTran(
            OdbcApi.SQL_HANDLE_DBC.toShort(),
            connectionHandle,
            OdbcApi.SQL_COMMIT.toShort()
        )
        if (!OdbcApi.isSuccess(result)) {
            val diag = OdbcDiagnostics.getDiagMessage(api, OdbcApi.SQL_HANDLE_DBC.toShort(), connectionHandle)
            throw SQLException("Erro ao fazer commit: $diag")
        }
    }

    override fun rollback() {
        checkNotClosed()
        if (autoCommit) throw SQLException("Não é possível fazer rollback em modo autoCommit")
        val result = api.SQLEndTran(
            OdbcApi.SQL_HANDLE_DBC.toShort(),
            connectionHandle,
            OdbcApi.SQL_ROLLBACK.toShort()
        )
        if (!OdbcApi.isSuccess(result)) {
            val diag = OdbcDiagnostics.getDiagMessage(api, OdbcApi.SQL_HANDLE_DBC.toShort(), connectionHandle)
            throw SQLException("Erro ao fazer rollback: $diag")
        }
    }

    override fun rollback(savepoint: Savepoint?) {
        throw SQLFeatureNotSupportedException("Savepoints não suportados neste driver")
    }

    // --- DatabaseMetaData ---

    override fun getMetaData(): DatabaseMetaData {
        checkNotClosed()
        return OdbcDatabaseMetaData(this, api, connectionHandle, charset)
    }

    // --- Sobrescritas com lógica real ---

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = createStatement()
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement = createStatement()

    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = prepareStatement(sql)
    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement = prepareStatement(sql)
    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement = prepareStatement(sql)
    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement = prepareStatement(sql)
    override fun prepareStatement(sql: String?, columnNames: Array<out String>?): PreparedStatement = prepareStatement(sql)

    override fun nativeSQL(sql: String?): String? = sql

    /**
     * Verifica se a conexão ainda está ativa, consultando o driver ODBC nativo.
     *
     * Utiliza SQL_ATTR_CONNECTION_DEAD (ODBC 3.x) para perguntar ao driver
     * se a conexão foi perdida. Se o driver não suportar o atributo,
     * usa a flag interna [connectionDead] como fallback.
     */
    override fun isValid(timeout: Int): Boolean {
        if (closed || connectionDead) return false
        return try {
            val dead = IntByReference()
            val result = api.SQLGetConnectAttr(
                connectionHandle,
                OdbcApi.SQL_ATTR_CONNECTION_DEAD,
                dead.pointer,
                4, // sizeof(SQLUINTEGER)
                null
            )
            if (OdbcApi.isSuccess(result)) {
                val isDead = dead.value == OdbcApi.SQL_CD_TRUE
                if (isDead) connectionDead = true
                !isDead
            } else {
                // Driver não suporta SQL_ATTR_CONNECTION_DEAD — usar flag interna
                !connectionDead
            }
        } catch (_: Exception) {
            connectionDead = true
            false
        }
    }

    // --- Stubs triviais ---

    override fun setReadOnly(readOnly: Boolean) {}
    override fun isReadOnly(): Boolean = false
    override fun setCatalog(catalog: String?) {}
    override fun getCatalog(): String? = null
    override fun setTransactionIsolation(level: Int) {}
    override fun getTransactionIsolation(): Int = Connection.TRANSACTION_READ_COMMITTED
    override fun getWarnings(): SQLWarning? = null
    override fun clearWarnings() {}
    override fun getTypeMap(): MutableMap<String, Class<*>> = mutableMapOf()
    override fun setTypeMap(map: MutableMap<String, Class<*>>?) {}
    override fun setHoldability(holdability: Int) {}
    override fun getHoldability(): Int = ResultSet.CLOSE_CURSORS_AT_COMMIT

    override fun setSavepoint(): Savepoint = throw SQLFeatureNotSupportedException("Savepoints não suportados")
    override fun setSavepoint(name: String?): Savepoint = throw SQLFeatureNotSupportedException("Savepoints não suportados")
    override fun releaseSavepoint(savepoint: Savepoint?) = throw SQLFeatureNotSupportedException("Savepoints não suportados")

    override fun createClob(): Clob = throw SQLFeatureNotSupportedException()
    override fun createBlob(): Blob = throw SQLFeatureNotSupportedException()
    override fun createNClob(): NClob = throw SQLFeatureNotSupportedException()
    override fun createSQLXML(): SQLXML = throw SQLFeatureNotSupportedException()

    override fun setClientInfo(name: String?, value: String?) {}
    override fun setClientInfo(properties: Properties?) {}
    override fun getClientInfo(name: String?): String? = null
    override fun getClientInfo(): Properties = Properties()

    override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array =
        throw SQLFeatureNotSupportedException()
    override fun createStruct(typeName: String?, attributes: Array<out Any>?): Struct =
        throw SQLFeatureNotSupportedException()

    override fun prepareCall(sql: String?): CallableStatement = throw SQLFeatureNotSupportedException("CallableStatement não suportado")
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = throw SQLFeatureNotSupportedException()
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement = throw SQLFeatureNotSupportedException()

    override fun setSchema(schema: String?) {}
    override fun getSchema(): String? = null
    override fun abort(executor: Executor?) { close() }
    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) {}
    override fun getNetworkTimeout(): Int = 0

    override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLFeatureNotSupportedException()
    override fun isWrapperFor(iface: Class<*>?): Boolean = false

    // --- Helpers privados ---

    /**
     * Aloca um handle ODBC para Statement.
     */
    private fun allocateStatementHandle(): Pointer {
        val stmtPtr = com.sun.jna.ptr.PointerByReference()
        val result = try {
            api.SQLAllocHandle(OdbcApi.SQL_HANDLE_STMT.toShort(), connectionHandle, stmtPtr)
        } catch (e: Exception) {
            throw SQLException("Erro de comunicação ao criar Statement ODBC: ${e.message}", e)
        }
        if (!OdbcApi.isSuccess(result)) {
            val diagMsg = OdbcDiagnostics.getDiagMessage(api, OdbcApi.SQL_HANDLE_DBC.toShort(), connectionHandle)
            throw SQLException("ODBC não conseguiu alocar Statement (Código: $result). $diagMsg")
        }
        return stmtPtr.value
    }

    /**
     * Marca a conexão como morta após um erro de comunicação.
     * Chamado internamente pelos Statement/PreparedStatement quando
     * detetam um SQLSTATE da classe 08 (connection exception).
     */
    internal fun markConnectionDead() {
        connectionDead = true
    }

    private fun checkNotClosed() {
        if (closed) throw SQLException("Connection já foi fechada", "08003")
        if (connectionDead) throw SQLException(
            "A conexão foi perdida (server disconnect). Reconecte.", "08S01"
        )
    }
}