package pt.daniel.odbc

import pt.daniel.odbc.interop.OdbcApi
import pt.daniel.odbc.interop.OdbcUnavailableException
import java.sql.*

/**
 * Implementação de [Statement] que executa SQL diretamente via ODBC.
 *
 * @param connection  A conexão "pai" deste statement.
 * @param api         API nativa ODBC injetada (permite mocking em testes).
 * @param stmtHandle  Handle ODBC do statement, alocado pelo driver.
 */
class OdbcStatement(
    private val connection: Connection,
    private val api: OdbcApi,
    private val stmtHandle: com.sun.jna.Pointer?
) : Statement {

    private var closed = false

    // --- Métodos com lógica ODBC real ---

    override fun executeQuery(sql: String?): ResultSet {
        checkNotClosed()
        execDirect(sql)
        // TODO: implementar OdbcResultSet com SQLFetch + SQLGetData
        throw SQLFeatureNotSupportedException("executeQuery: OdbcResultSet ainda não implementado")
    }

    override fun executeUpdate(sql: String?): Int {
        checkNotClosed()
        execDirect(sql)
        return 0 // TODO: chamar SQLRowCount para saber quantas linhas foram afetadas
    }

    override fun execute(sql: String?): Boolean {
        checkNotClosed()
        execDirect(sql)
        return false // false = não há ResultSet (DDL/DML simples)
    }

    override fun close() {
        if (!closed) {
            try {
                api.SQLFreeHandle(OdbcApi.SQL_HANDLE_STMT.toShort(), stmtHandle)
            } finally {
                closed = true
            }
        }
    }

    override fun isClosed(): Boolean = closed

    override fun getConnection(): Connection = connection

    // --- Helpers privados ---

    private fun execDirect(sql: String?) {
        requireNotNull(sql) { "O SQL não pode ser nulo" }
        val result = try {
            api.SQLExecDirect(stmtHandle, sql, sql.length)
        } catch (e: Exception) {
            throw SQLException("Erro de comunicação ao executar SQL via ODBC: ${e.message}", e)
        }
        if (result.toInt() !in listOf(OdbcApi.SQL_SUCCESS, OdbcApi.SQL_SUCCESS_WITH_INFO)) {
            throw SQLException("ODBC devolveu erro ao executar SQL (Código: $result)")
        }
    }

    private fun checkNotClosed() {
        if (closed) throw SQLException("Statement já foi fechado")
    }

    // --- Stubs obrigatórios da interface Statement ---

    override fun getMaxFieldSize(): Int = 0
    override fun setMaxFieldSize(max: Int) {}
    override fun getMaxRows(): Int = 0
    override fun setMaxRows(max: Int) {}
    override fun setEscapeProcessing(enable: Boolean) {}
    override fun getQueryTimeout(): Int = 0
    override fun setQueryTimeout(seconds: Int) {}
    override fun cancel() {}
    override fun getWarnings(): SQLWarning? = null
    override fun clearWarnings() {}
    override fun setCursorName(name: String?) {}
    override fun getResultSet(): ResultSet? = null
    override fun getUpdateCount(): Int = -1
    override fun getMoreResults(): Boolean = false
    override fun setFetchDirection(direction: Int) {}
    override fun getFetchDirection(): Int = ResultSet.FETCH_FORWARD
    override fun setFetchSize(rows: Int) {}
    override fun getFetchSize(): Int = 0
    override fun getResultSetConcurrency(): Int = ResultSet.CONCUR_READ_ONLY
    override fun getResultSetType(): Int = ResultSet.TYPE_FORWARD_ONLY
    override fun addBatch(sql: String?) {}
    override fun clearBatch() {}
    override fun executeBatch(): IntArray = intArrayOf()
    override fun getMoreResults(current: Int): Boolean = false
    override fun getGeneratedKeys(): ResultSet? = null
    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int = executeUpdate(sql)
    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int = executeUpdate(sql)
    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int = executeUpdate(sql)
    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean = execute(sql)
    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean = execute(sql)
    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean = execute(sql)
    override fun getResultSetHoldability(): Int = ResultSet.CLOSE_CURSORS_AT_COMMIT
    override fun setPoolable(poolable: Boolean) {}
    override fun isPoolable(): Boolean = false
    override fun closeOnCompletion() {}
    override fun isCloseOnCompletion(): Boolean = false
    override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLFeatureNotSupportedException()
    override fun isWrapperFor(iface: Class<*>?): Boolean = false
}
