/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-library`
    `maven-publish`
}

version = project.findProperty("version") ?: "1.0.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.kotlin.stdlib)
    implementation(libs.jna)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

val currentVersion = version.toString()
val propFileRelativePath = "pt/daniel/odbc/version.properties"

tasks.register("generateVersionProperties") {
    val outputDir = layout.buildDirectory.dir("generated/resources")
    inputs.property("version", currentVersion)
    outputs.dir(outputDir)
    doLast {
        val propFile = outputDir.get().file(propFileRelativePath).asFile
        propFile.parentFile.mkdirs()
        propFile.writeText("version=$currentVersion")
    }
}



sourceSets {
    main {
        kotlin.setSrcDirs(listOf("src/main/kotlin"))
        resources.srcDir(tasks.named("generateVersionProperties"))
    }
}



tasks.register<Jar>("fatJar") {
    archiveClassifier.set("all")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    // Inclui as classes do projeto
    from(sourceSets.main.get().output)
    
    // Inclui todas as dependências (Kotlin, JNA, etc.)
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) {
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
    }

    manifest {
        attributes["Implementation-Title"] = "JDBC-ODBC Bridge Fat JAR"
        attributes["Implementation-Version"] = project.version
    }
}

tasks.register<Copy>("copyDependencies") {
    from(configurations.runtimeClasspath)
    into(layout.buildDirectory.dir("libs/deps"))
}

tasks.named("build") {
    dependsOn("copyDependencies", "fatJar")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "pt.daniel.odbc"
            artifactId = "jdbc-odbc-bridge"
            version = currentVersion

            // Publica o fatJar como o arquivo principal
            artifact(tasks.named("fatJar"))
        }
    }
}